comment:
  layout: ' diff, flags, files' # 코멘트에 표시할 항목 (변경사항, 플래그, 파일별 커버리지)
  behavior: default # 코멘트 동작 방식 (기본값: 항상 새 코멘트 작성)
  require_changes: false # false: 커버리지 변경이 없어도 코멘트를 생성
  require_base: false # false: base 리포트 없이도 코멘트 생성 가능
  require_head: true # true: head 리포트가 있어야 코멘트를 생성
  hide_project_coverage: false # false: 프로젝트 전체 커버리지도 보여줌
coverage:
  # precision: 2                        # 커버리지 소수점 이하 자릿수
  # range: "70...100"                   # 최소-최대 커버리지 범위
  status:
    # project: true                     # 프로젝트 전체 커버리지 체크
    patch: true # PR에서 변경된 코드 커버리지 체크
    changes: true # PR에서 변경된 파일만 체크
