version: 2.1
orbs:
  # "cypress-io/cypress@3" installs the latest published
  # version "s.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@3.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@3
executors:
  node-executor:
    docker:
      - image: cypress/base:18.17.0 # Node.js 버전을 18.17.0 이상으로 설정
jobs:
  build_and_test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run build
      - run:
          name: Start Server
          command: npm run start &
      - run:
          name: Wait for Server
          command: npx wait-on http://localhost:3000
      - cypress/run:
          start: npm run start
          wait-on: http://localhost:3000
workflows:
  build:
    jobs:
      - build_and_test
