name: '✅ TEST'
description: '테스트 케이스 작성 템플릿'
title: '[✅ Test] 제목'
labels: ['✅ Test']
body:
  - type: input
    id: test_overview
    attributes:
      label: '📄 테스트 개요'
      description: '테스트할 기능에 대한 간략한 설명을 작성해주세요.'
      placeholder: '예: 로그인 기능 테스트'
    validations:
      required: true

  - type: textarea
    id: test_scenario
    attributes:
      label: '테스트 시나리오'
      description: '테스트할 시나리오를 단계별로 작성해주세요.'
      placeholder: |
        예:
          1. 로그인 페이지로 이동
          2. 유효한 사용자 정보 입력
          3. 로그인 버튼 클릭
    validations:
      required: true

  - type: textarea
    id: expected_result
    attributes:
      label: '예상 결과'
      description: '테스트 시나리오에 따른 예상 결과를 작성해주세요.'
      placeholder: '예: 사용자 대시보드로 이동해야 합니다.'
    validations:
      required: true

  - type: textarea
    id: actual_result
    attributes:
      label: '실제 결과'
      description: '테스트 실행 후 실제 결과를 작성해주세요.'
      placeholder: '실제 결과를 입력해주세요.'
