name: '🐛 BUG'
description: '버글 발생/해결 템플릿'
title: '🐛 [Bug] 제목'
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        ✅ 기능이 구현되지 않거나 예상과 다르게 작동하는 경우:
        - 구현하고자 한 기능, 작성한 코드, 구현 방식 등을 상세히 설명하고, 문제가 발생한 에러 메시지를 첨부해주세요.
        - 필요시 이미지나 동영상을 함께 첨부해주세요.

        ✅ 문제 해결 시:
        - 제목에 Bug 이슈 번호를 포함하고, 문제 원인과 해결 방법을 코드와 함께 설명해주세요. (참고 링크가 있다면 함께 작성)

        - 필수 내용: 문제 상황, 코드, 에러 메시지, 이슈 번호 (해결한 경우)
        - 선택 사항: 이미지, 동영상, 참고 링크

        ✅ labels와 assignees를 연결해주세요.
        ✅ 작업 완료 후, projects, milestones, developments를 연결해주세요.

  - type: textarea
    attributes:
      label: 📄 문제상황
      description: 문제 상황을 상세하게 작성해주세요.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: ✔️ 재현 가능 여부
      description: 확인한 버그 상황을 재현 가능한지 여부를 체크해주세요.
      options:
        - label: '예'
        - label: '아니오'
  - type: textarea
    attributes:
      label: 💻 코드
      description: "코드 첨부시, VS Code 캡쳐본과 함께 해당 코드를 복사해서 올려주세요. \n 에러메시지가 있는 경우, 에러메시지 캡쳐본과 함께 에러메시지를 복사해서 올려주세요"
  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 이미지, 동영상, 참고 링크
